# Generated by Django 5.0.7 on 2025-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('avatar', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/')),
                ('joined', models.DateField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'НовыйПользователь',
                'verbose_name_plural': 'НовыеПользователи',
            },
        ),
    ]
