# Generated by Django 5.0.7 on 2025-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('attraction', 'Достопримечательность'), ('cafe', 'Кафе'), ('park', 'Парк')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
